import type { Metadata } from "next";
import { manrope, fraunces } from "@/app/Fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Workit Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fraunces.className}>{children}</body>
    </html>
  );
}
